name    'iksteen-lxc'
version '0.0.2'
source  'git://github.com/iksteen/puppet-lxc.git'
author  'Ingmar Steen <iksteen@gmail.com>'
license 'Apache License, Version 2.0'
summary 'lxc module'
description 'Provision and manage lxc containers using puppet'
project_page 'http://github.com/iksteen/puppet-lxc'

dependency 'puppetlabs-stdlib', '>= 3.2.0'
dependency 'fiddyspence-sysctl', '>= 0.0.4'
dependency 'puppetlabs-firewall', '>= 0.2.1'
